version: '3.7'
services:
        
   front-app:
    build: .
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - "/app/node_modules"
      - ".:/app"
      
networks:
  currency-compose-network: